### ISSUE TITLE
关于3.9 torch高版本 requirement_for_higher version_torch.txt 当中numpy版本的问题

### ISSUE THREAD

**Issue by dhyuk54** [hongwang01/InDuDoNet#17]
当我按照您 train的步骤运行了之后 出现了ValueError的问题。
这是我目前的环境  Ubuntu18.04  python3.9 
Package                 Version
----------------------- ---------------
absl-py                 2.1.0
astra-toolbox           2.1.2
Brotli                  1.0.9
cachetools              5.5.0
certifi                 2024.8.30
charset-normalizer      3.3.2
cycler                  0.12.1
future                  1.0.0
google-auth             2.35.0
google-auth-oauthlib    0.4.6
grpcio                  1.66.1
h5py                    3.10.0
idna                    3.7
importlib_metadata      8.5.0
joblib                  1.4.2
kiwisolver              1.4.7
Markdown                3.7
MarkupSafe              2.1.5
matplotlib              3.1.1
mkl_fft                 1.3.10
mkl_random              1.2.7
mkl-service             2.4.0
numpy                   2.0.1
oauthlib                3.2.2
odl                     1.0.0.dev0
packaging               24.1
pillow                  10.4.0
pip                     24.2
protobuf                3.19.6
pyasn1                  0.6.1
pyasn1_modules          0.4.1
pyparsing               3.1.4
PySocks                 1.7.1
python-dateutil         2.9.0.post0
PyYAML                  6.0.2
requests                2.32.3
requests-oauthlib       2.0.0
rsa                     4.9
scikit-learn            1.4.2
scipy                   1.13.1
setuptools              75.1.0
six                     1.16.0
tb-nightly              2.11.0a20220906
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorboardX            1.8
threadpoolctl           3.5.0
torch                   1.13.1
torchaudio              0.13.1
torchvision             0.14.1
tqdm                    4.66.1
typing_extensions       4.11.0
tzdata                  2024.1
urllib3                 2.1.0
wcwidth                 0.2.13
Werkzeug                3.0.2
wheel                   0.44.0
yacs                    0.1.8
zipp                    3.20.2

当我运行 CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/"
之后 
:~/InDuDoNet# CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/"
Traceback (most recent call last):
  File "/root/InDuDoNet/train.py", line 23, in <module>
    from deeplesion.Dataset import MARTrainDataset
  File "/root/InDuDoNet/deeplesion/__init__.py", line 1, in <module>
    from .Dataset import MARTrainDataset
  File "/root/InDuDoNet/deeplesion/Dataset.py", line 5, in <module>
    import h5py
  File "/root/miniconda3/envs/my39/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
    from . import _errors
  File "h5py/_errors.pyx", line 1, in init h5py._errors
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

出现了ValueError 错误 ，想请问 博主您的3.9 torch高版本的 numpy 版本是多少呢？ 其他的lib装的还是没有问题的。
期待您的回复，谢谢

**Comment by hongwang01** [comment]
> 当我按照您 train的步骤运行了之后 出现了ValueError的问题。 这是我目前的环境 Ubuntu18.04 python3.9 Package Version
> 
> absl-py 2.1.0 astra-toolbox 2.1.2 Brotli 1.0.9 cachetools 5.5.0 certifi 2024.8.30 charset-normalizer 3.3.2 cycler 0.12.1 future 1.0.0 google-auth 2.35.0 google-auth-oauthlib 0.4.6 grpcio 1.66.1 h5py 3.10.0 idna 3.7 importlib_metadata 8.5.0 joblib 1.4.2 kiwisolver 1.4.7 Markdown 3.7 MarkupSafe 2.1.5 matplotlib 3.1.1 mkl_fft 1.3.10 mkl_random 1.2.7 mkl-service 2.4.0 numpy 2.0.1 oauthlib 3.2.2 odl 1.0.0.dev0 packaging 24.1 pillow 10.4.0 pip 24.2 protobuf 3.19.6 pyasn1 0.6.1 pyasn1_modules 0.4.1 pyparsing 3.1.4 PySocks 1.7.1 python-dateutil 2.9.0.post0 PyYAML 6.0.2 requests 2.32.3 requests-oauthlib 2.0.0 rsa 4.9 scikit-learn 1.4.2 scipy 1.13.1 setuptools 75.1.0 six 1.16.0 tb-nightly 2.11.0a20220906 tensorboard-data-server 0.6.1 tensorboard-plugin-wit 1.8.1 tensorboardX 1.8 threadpoolctl 3.5.0 torch 1.13.1 torchaudio 0.13.1 torchvision 0.14.1 tqdm 4.66.1 typing_extensions 4.11.0 tzdata 2024.1 urllib3 2.1.0 wcwidth 0.2.13 Werkzeug 3.0.2 wheel 0.44.0 yacs 0.1.8 zipp 3.20.2
> 
> 当我运行 CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/" 之后 :~/InDuDoNet# CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/" Traceback (most recent call last): File "/root/InDuDoNet/train.py", line 23, in from deeplesion.Dataset import MARTrainDataset File "/root/InDuDoNet/deeplesion/**init**.py", line 1, in from .Dataset import MARTrainDataset File "/root/InDuDoNet/deeplesion/Dataset.py", line 5, in import h5py File "/root/miniconda3/envs/my39/lib/python3.9/site-packages/h5py/**init**.py", line 25, in from . import _errors File "h5py/_errors.pyx", line 1, in init h5py._errors ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> 
> 出现了ValueError 错误 ，想请问 博主您的3.9 torch高版本的 numpy 版本是多少呢？ 其他的lib装的还是没有问题的。 期待您的回复，谢谢

感谢对我们工作关注。 抱歉，numpy==1.26.3，我们已经补充到requirement中，谢谢。

**Comment by dhyuk54** [comment]
> > 当我按照您 train的步骤运行了之后 出现了ValueError的问题。 这是我目前的环境 Ubuntu18.04 python3.9 Package Version
> > absl-py 2.1.0 astra-toolbox 2.1.2 Brotli 1.0.9 cachetools 5.5.0 certifi 2024.8.30 charset-normalizer 3.3.2 cycler 0.12.1 future 1.0.0 google-auth 2.35.0 google-auth-oauthlib 0.4.6 grpcio 1.66.1 h5py 3.10.0 idna 3.7 importlib_metadata 8.5.0 joblib 1.4.2 kiwisolver 1.4.7 Markdown 3.7 MarkupSafe 2.1.5 matplotlib 3.1.1 mkl_fft 1.3.10 mkl_random 1.2.7 mkl-service 2.4.0 numpy 2.0.1 oauthlib 3.2.2 odl 1.0.0.dev0 packaging 24.1 pillow 10.4.0 pip 24.2 protobuf 3.19.6 pyasn1 0.6.1 pyasn1_modules 0.4.1 pyparsing 3.1.4 PySocks 1.7.1 python-dateutil 2.9.0.post0 PyYAML 6.0.2 requests 2.32.3 requests-oauthlib 2.0.0 rsa 4.9 scikit-learn 1.4.2 scipy 1.13.1 setuptools 75.1.0 six 1.16.0 tb-nightly 2.11.0a20220906 tensorboard-data-server 0.6.1 tensorboard-plugin-wit 1.8.1 tensorboardX 1.8 threadpoolctl 3.5.0 torch 1.13.1 torchaudio 0.13.1 torchvision 0.14.1 tqdm 4.66.1 typing_extensions 4.11.0 tzdata 2024.1 urllib3 2.1.0 wcwidth 0.2.13 Werkzeug 3.0.2 wheel 0.44.0 yacs 0.1.8 zipp 3.20.2
> > 当我运行 CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/" 之后 :~/InDuDoNet# CUDA_VISIBLE_DEVICES=0 python train.py --data_path "deeplesion/train/" --log_dir "logs" --model_dir "pretrained_model/" Traceback (most recent call last): File "/root/InDuDoNet/train.py", line 23, in from deeplesion.Dataset import MARTrainDataset File "/root/InDuDoNet/deeplesion/**init**.py", line 1, in from .Dataset import MARTrainDataset File "/root/InDuDoNet/deeplesion/Dataset.py", line 5, in import h5py File "/root/miniconda3/envs/my39/lib/python3.9/site-packages/h5py/**init**.py", line 25, in from . import _errors File "h5py/_errors.pyx", line 1, in init h5py._errors ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> > 出现了ValueError 错误 ，想请问 博主您的3.9 torch高版本的 numpy 版本是多少呢？ 其他的lib装的还是没有问题的。 期待您的回复，谢谢
> 
> 感谢对我们工作关注。 抱歉，numpy==1.26.3，我们已经补充到requirement中，谢谢。

谢谢您的回复
